### ISSUE TITLE
JavaOutOfMemoryError: Java Heap Space

### ISSUE THREAD

**Issue by snoobi-seggs** [ffauzan/id-look#1]
running /gm will result in this error on the console. 
already attempted to increase java heap space to 16GB and still result in the same error

**Comment by ffauzan** [comment]
I think there is a memory leak bug, try the v1.0.1 and let me know if the memory leak still happens. Thanks.
[v1.0.1](https://github.com/ffauzan/id-look/releases/tag/v1.0.1)

**Comment by RalphYeo0** [comment]
v1.0.1 (already compiled version) no longer gives a out of mem error, however it also returns "cannot find anything, try different keyword" error for every item searched

**Comment by snoobi-seggs** [comment]
it now throws the error at server launch

**Comment by ffauzan** [comment]
> it now throws the error at server launch

What kind of error?
I tested on Grasscutter version 1.2.2-dev and 1.2.0

**Comment by snoobi-seggs** [comment]
late reply , but is the same error as before(JavaOutOfMemorError: Java Heap Space), just that its at server launch instead of when the command is ran
